### ISSUE TITLE
Configuration file for annotation attributes and values

### ISSUE THREAD

**Issue by piekvossen** [cltl/EMISSOR#43]
Allow for loading a configuration file with annotation attributes and values that can be used in the interface as drop down items to tag certain modalities

**Comment by numblr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GMRC](https://trello.com/c/B7dA9krD/7-gmrc)

**Comment by selBaez** [comment]
Define attributes and values

1) hardcoded
2) load from ontology/brain (suggestions based on things mentioned the most or more recently)
3) dynamic read/write to brain

**Comment by numblr** [comment]
We implemented the backend, frontend is moved to #59.
