### ISSUE TITLE
ModuleNotFoundError: No module named 'tests.test_emissor'

### ISSUE THREAD

**Issue by jaapkruijt** [cltl/EMISSOR#62]
While running lets-chat.ipynb on a Windows machine, I get the following error in the 3rd cell (containing various import statements):

`ModuleNotFoundError                       Traceback (most recent call last)`
`~\AppData\Local\Temp/ipykernel_11292/2173937830.py in <module>`
`     10 import cv2`
`     11 from datetime import datetime`
`---> 12 import tests.test_emissor.test_interaction.driver_util as util`

`ModuleNotFoundError: No module named 'tests.test_emissor'`

It seems like it can't find the correct folder (tests.test_emissor.test_interaction), however the file driver_util.py does exist under these folders

**Comment by tae898** [comment]
Can you write more detailed error messages / logs?

**Comment by tae898** [comment]
Below is the current code:

```
import os
import spacy
import time
import uuid
from datetime import datetime
from emissor.persistence import ScenarioStorage
from emissor.representation.annotation import AnnotationType, Token, NER
from emissor.representation.container import Index
from emissor.representation.scenario import Modality, ImageSignal, TextSignal, Mention, Annotation, Scenario
import cv2
from datetime import datetime
import driver_util as util
```

I can't find `import tests.test_emissor.test_interaction.driver_util as util`. Did you add this yourself?

**Comment by jaapkruijt** [comment]
No I did not, but it must have been updated then. Thanks for pointing this out, this solved the issue
